theme = "kanagawa"

[editor]
line-number = "relative"
completion-replace = true
auto-format = false

[editor.file-picker]
hidden = false


[editor.statusline]
left = ["mode", "spinner","file-name"]
center = []
right = ["file-modification-indicator" ,"diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[keys.normal]
f = ":format"
