theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
completion-timeout = 5
completion-replace = true
auto-format = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


[editor.statusline]
left = ["mode", "spinner","file-name"]
center = []
right = ["file-modification-indicator" ,"diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[keys.normal]
f = ":format"
